export const routes = {
  auth: {
    signUp: "/sign-up",
    forgotPassword: "/forgot-password",
    otp: "/auth/otp",
  },
  signIn: "/login",
  publicUrl: (id: string) => `/tracking/${id}`,
  testing: "/testing",
  orders: {
    orders: "/orders",
    shipperInfo: "/shipper-info",
    createShipperInfo: "/add-shipper-info",
    createOrder: "/create-orders",
    editOrder: (id: string) => `/create-orders/${id}`,
    orderDetail: (id: string) => `/orders/${id}`,
    confirmOrders: "/orders/confirm-orders",
    resellingOrders: "/orders/reselling-orders",
    booking: "/orders/booking",
    dispatch: "/dispatch",
    procure: "/procure",
    pickedUp: "/picked-up",
    loadSheets: "/load-sheets",
    CreateLoadSheet: "/create-loadsheet",
    manualBooking: "/manual-booking",
    cprCheques: "/cpr-cheques",
    tracking: "/tracking",
  },
  products: {
    products: "/products",
    categories: "/categories",
    createCategories: "/create-categories",
    inventory: "/inventory",
    createProducts: "/create-products",
    purchaseOrders: "/purchaseOrder",
    ediProduct: (slug: string) => `/products/${slug}/edit`,
  },
  reselling: {
    resellingProduct: "/reselling-product",
    myResellers: "/my-resellers",
    resellersProduct: "/resellers-product",
    listProducts: "/list-products",
    resellingOrders: "/reselling-orders",
    createResellingOrder: "/create-reselling-order",
    showCase: "/reselling-product",
    myOrders: "/my-orders",
  },
  reports: "/reports",
  customer: "/customer",
  questionnaire: "/questionnaire",
  settings: {
    stores: {
      channels: "/sales-channel",
      saleChannelsQuestionnaire: "/sales-channel/questionnaire",
      channelDetail: (id: string) => `/sales-channel/${id}`,
      skuMapping: "/stores/sku-mapping",
      inventory: "/stores/inventory",
      shipperInfo: "/shipper-info",
      addInfo: "/add-info",
      addChannel: "/add-channels",
    },
    couriers: {
      courierManagement: "/courier-management",
      bookingCities: "/settings/couriers/booking-cities",
    },
    forms: {
      profileSettings: "/profile-settings",
      notificationPreference: "/profile-settings/notification",
      personalInformation: "/profile-settings/profile",
      newsletter: "/forms/newsletter",
    },
    userPermissions: "/settings/user-permissions",
    billing: "/billing",
  },
  payments: {
    dashboard: "/dashboard",
    history: {
      viewDetails: {
        print: "/print",
      },
      dispute: "/dispute",
    },
  },
  rolesPermissions: "/roles-permissions",
  eCommerce: {
    dashboard: "/ecommerce",
    products: "/ecommerce/products",
    createProduct: "/ecommerce/products/create",
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: "/ecommerce/categories",
    createCategory: "/ecommerce/categories/create",
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: "/ecommerce/orders",
    createOrder: "/ecommerce/orders/create",
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: "/ecommerce/reviews",
    shop: "/ecommerce/shop",
    cart: "/ecommerce/cart",
    checkout: "/ecommerce/checkout",
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  invoice: {
    home: "/invoice",
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
    builder: "/invoice/builder",
  },
  salesManagement: "/sales-management",
  purchaseOrder: "/purchaseOrder",
};
